version: '3.8'

services:
  dimetuverdad:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./accounts.db:/app/accounts.db
      - ./.env:/app/.env:ro
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-change-this-in-production}
      - ADMIN_TOKEN=${ADMIN_TOKEN:-admin123}
    networks:
      - dimetuverdad-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - dimetuverdad-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  ollama_data:

networks:
  dimetuverdad-network:
    driver: bridge